spring:
  application:
    name: liteflow-agent-jev
  config:
    import: optional:classpath:application-local.yml

server:
  port: 8906

liteflow:
  rule-source: classpath:flow.el.xml
  agent:
    jev:
      provider: typesafe
      api-key: ${JEV_API_KEY:}